service: layer-test-lambda

package:
  individually: true
  
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage,'dev'}
  memorySize: 128
  lambdaHashingVersion: 20201221
  
functions:
  test:
    name: ${self:service}-test-${self:provider.stage}
    handler: src/test.handler
    layers:
      - ${cf:layer-test-layer-${self:provider.stage}.Layer1Export}
